---
name: healthchecks
version: 3.1.2
slug: healthchecks
description: Healthchecks 是一个用于监控你的cron作业的守护程序。它是一个监听来自你的cron作业ping请求的网络服务器，并且还有一个网络界面。
  Healthchecks is a watchdog for your cron jobs.
  It's a web server that listens for pings from your cron jobs, plus a web interface.
arch:
  - aarch64
  - amd64
image: "ghcr.nju.edu.cn/bluemaex/ha-addons-healthchecks-{arch}"
startup: system
url: https://gh-proxy.com/github.com/bluemaex/home-assistant-addons/tree/master/healthchecks
init: false
ingress: true
ingress_port: 8000
panel_icon: mdi:timer-check-outline
ports:
  8000/tcp: null
  2525/tcp: 2525
ports_description:
  8000/tcp: Healthchecks Web UI
  2525/tcp: Port for inbound SMTP pings
map:
  - config
  - ssl
options:
  env_vars: []
schema:
  env_vars:
    - str?
