---
version: 1.8.1
slug: dnsmasq
name: Dnsmasq
description: $'简单DNS服务器

请注意，由于您没有给出具体的上下文或背景信息，这个翻译可能并不完全准确。如果您需要更精确的翻译，请提供更多的上下文或详细信息。'
url: https://gh-proxy.com/github.com/home-assistant/addons/tree/master/dnsmasq
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: docker.m.daocloud.io/homeassistant/{arch}-addon-dnsmasq
init: false
options:
  defaults:
    - 8.8.8.8
    - 8.8.4.4
  forwards: []
  hosts: []
  services: []
  cnames: []
  log_queries: false
  cache_size: 150
ports:
  53/tcp: 53
  53/udp: 53
schema:
  defaults:
    - str
  forwards:
    - domain: str
      server: str
  hosts:
    - host: str
      ip: str
  services:
    - host: str
      port: str
      priority: int
      srv: str
      weight: int
  cnames:
    - name: str
      target: str
  log_queries: bool
  cache_size: int
startup: system
