# https://gh-proxy.com/github.com/AlexxIT/builder/blob/master/builder.sh
name: go2rtc master hardware
description: 英特尔（VAAPI/QSV）、AMD（VAAPI）和英伟达（CUDA）的硬件转码。
url: https://gh-proxy.com/github.com/AlexxIT/go2rtc
image: alexxit/go2rtc
arch: [ amd64 ]

# https://developers.home-assistant.io/docs/add-ons/configuration
version: master-hardware
slug: go2rtc-master-hw
init: false
startup: system
host_network: true
homeassistant_api: true
full_access: true
video: true
audio: true
ingress: true
ingress_port: 1984
panel_icon: mdi:camera-wireless
map: [ "config:rw", "media", "ssl" ]