---
build_from:
  aarch64: ghcr.nju.edu.cn/home-assistant/aarch64-base:3.15
  amd64: ghcr.nju.edu.cn/home-assistant/amd64-base:3.15
  armhf: ghcr.nju.edu.cn/home-assistant/armhf-base:3.15
  armv7: ghcr.nju.edu.cn/home-assistant/armv7-base:3.15
  i386: ghcr.nju.edu.cn/home-assistant/i386-base:3.15
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  TELLDUS_COMMIT: 2598bbed16ffd701f2a07c99582f057a3decbaf3
