name: Music Assistant Server (dev/nightly)
# version number gets updated only when the mass base image updates!
version: 1.2.3
slug: music_assistant_dev
description: $'音乐助理的开发（ nightly）版本。此附加组件在启动时直接从git安装最新版本的分支。（可配置）。如果你想跟上最新的开发进度，但使用它时要自行承担风险，不建议日常使用。只需重新启动附加组件即可获取最新版本。

翻译结果：

音乐助理的开发版（夜间版）。这个插件会在启动时直接从Git安装最新版本的分支（可配置）。如果你想要跟上最新的开发进度，但需要自己承担风险，不建议日常使用。只需重启插件就可以获取最新版本了。'
  This add-on installs the latest version from the (configurable) branch directly from git at startup.
  Install this version if you want to keep up with the latest bleeding edge development but use it at your own risk, not recomended for daily use.
  Simply restart the add-on to fetch the latest version from source.
url: https://music-assistant.io
arch:
  - amd64
  - aarch64
homeassistant_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 8095
panel_icon: mdi:play-circle
panel_title: Music Assistant
panel_admin: false
uart: false
map:
  - media:rw
init: false
advanced: false
stage: experimental
tmpfs: true
backup_exclude:
  - cache.db
  - collage_images/*
  - .cache/*
options:
  log_level: info
  branch: dev
  safe_mode: false
schema:
  log_level: list(debug|info|warning|error)
  branch: str
  safe_mode: bool
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
