name: Example
version: 10.1.0
slug: example
description: $'社区Home Assistant插件示例

（微笑表情）'
url: https://gh-proxy.com/github.com/hassio-addons/addon-example
codenotary: codenotary@frenck.dev
init: false
arch:
- aarch64
- amd64
- armv7
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
image: ghcr.nju.edu.cn/hassio-addons/example/{arch}
