name: Example
version: 10.1.0
slug: example
description: $'社区家庭助手的附加组件示例

注：由于“Community Home Assistant Add-ons”是专有名词，无法直接进行翻译。如果需要进一步的帮助，请告诉我更多相关信息。'
url: https://gh-proxy.com/github.com/hassio-addons/addon-example
codenotary: codenotary@frenck.dev
init: false
arch:
- aarch64
- amd64
- armv7
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
image: ghcr.nju.edu.cn/hassio-addons/example/{arch}
