name: PicoTTS
version: 1.6.1-migrate
slug: picotts
description: 🚨 Addons are moved to https://gh-proxy.com/github.com/Poeschl-HomeAssistant-Addons/repository
url: https://gh-proxy.com/github.com/Poeschl/Hassio-Addons/tree/main/picoTTS
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: ghcr.nju.edu.cn/poeschl-homeassistant-addons/picotts-{arch}
init: false
ports:
  59126/tcp: 59126
ports_description:
  59126/tcp: Http interface of the REST wrapper
homeassistant_api: true
