name: Get HACS
version: "1.3.1"
slug: get
image: "ghcr.nju.edu.cn/hacs/{arch}-addon-get"
description: $'获取HACS（Home Assistant Community Store）的最简单方法：

1. 打开你的Home Assistant界面。
2. 点击左上角的菜单按钮（三个水平线图标）。
3. 在下拉菜单中找到并点击“Store”选项。
4. 在Store页面中搜索“HACS”。
5. 找到HACS后，点击安装。

这样，你就成功地将HACS添加到了你的Home Assistant中。'
startup: once
boot: manual
url: "https://gh-proxy.com/github.com/hacs/addons/tree/main/get"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
schema:
  channel: list(current|development)?
map:
  - homeassistant_config:rw
