name: Authelia
version: 0.1.3
slug: authelia
description: $'认证和授权服务器

请注意，由于“Server”一词在英语中是中性词，没有性别之分，因此将其翻译为中文时通常也使用中性词。然而，在某些情况下，如果需要体现服务器的角色或功能，可能会选择一个更具体的词汇来描述它。例如，“认证服务器”可以表示负责验证用户身份的服务器，“授权服务器”则可能指的是管理访问权限的服务器。但在这里，“Authentication and Authorization Server”直接翻译为“认证和授权服务器”已经足够准确且通用了。'
url: https://gh-proxy.com/github.com/einschmidt/addon-authelia
arch:
- amd64
- aarch64
init: false
ports:
  9091/tcp: 9091
ports_description:
  9091/tcp: Authelia Web UI and API
map:
- addon_config:rw
options:
  domain: example.com
  log_level: info
schema:
  domain: str
  log_level: list(debug|info|warn|error)
image: ghcr.nju.edu.cn/einschmidt/authelia/{arch}
