build_from:
  armhf: "ghcr.nju.edu.cn/hassio-addons/base:17.1.5"
  armv7: "ghcr.nju.edu.cn/hassio-addons/base:17.1.5"
  aarch64: "ghcr.nju.edu.cn/hassio-addons/base:17.1.5"
  amd64: "ghcr.nju.edu.cn/hassio-addons/base:17.1.5"
  i386: "ghcr.nju.edu.cn/hassio-addons/base:17.1.5"
