# https://gh-proxy.com/github.com/AlexxIT/builder/blob/master/builder.sh
name: go2rtc
description: "Intel (VAAPI) 和 Raspberry (V4L2) 的硬件转码"
url: https://gh-proxy.com/github.com/AlexxIT/go2rtc
image: alexxit/go2rtc
arch: [ amd64, aarch64, i386, armv7 ]

# https://developers.home-assistant.io/docs/add-ons/configuration
version: 1.9.8
slug: go2rtc
init: false
startup: system
host_network: true
homeassistant_api: true
video: true
audio: true
ingress: true
ingress_port: 1984
panel_icon: mdi:camera-wireless
map: [ "config:rw", "media", "ssl" ]
