# https://gh-proxy.com/github.com/AlexxIT/builder/blob/master/builder.sh
name: go2rtc
description: $'硬件转码Intel（VAAPI）和树莓派（V4L2）

注：VAAPI是Intel提供的视频加速API，用于在Intel GPU上实现硬件加速的视频解码和编码。V4L2是Linux下的视频输入输出接口标准，支持多种视频采集设备。'
url: https://gh-proxy.com/github.com/AlexxIT/go2rtc
image: alexxit/go2rtc
arch: [ amd64, aarch64, i386, armv7 ]

# https://developers.home-assistant.io/docs/add-ons/configuration
version: 1.9.8
slug: go2rtc
init: false
startup: system
host_network: true
homeassistant_api: true
video: true
audio: true
ingress: true
ingress_port: 1984
panel_icon: mdi:camera-wireless
map: [ "config:rw", "media", "ssl" ]
