---
build_from:
  amd64: ghcr.nju.edu.cn/home-assistant/amd64-base-debian:bookworm
  aarch64: ghcr.nju.edu.cn/home-assistant/aarch64-base-debian:bookworm
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  HOMEASSISTANT_SATELLITE_VERSION: v2.2.0
