---
url: https://next.esphome.io/
arch:
- amd64
- aarch64
hassio_api: true
auth_api: true
host_network: true
ingress: true
ingress_port: 0
panel_icon: mdi:chip
uart: true
ports:
  6052/tcp: null
map:
- ssl:ro
- config:rw
discovery:
- esphome
schema:
  status_use_ping: bool?
  streamer_mode: bool?
  home_assistant_dashboard_integration: bool?
  default_compile_process_limit: int(1,)?
  esphome_fork: str?
  ssl: bool?
  certfile: str?
  keyfile: str?
  leave_front_door_open: bool?
backup_exclude:
- '*/*/'
init: false
startup: services
name: ESPHome Device Builder (dev)
panel_title: ESPHome Builder (dev)
version: 2025.3.0-dev20250308
slug: esphome-dev
description: $'ESPHome 设备构建器开发版

请注意，这个翻译是基于您提供的文本片段进行的。如果您有其他需要翻译的内容，请随时告诉我！'
image: ghcr.nju.edu.cn/esphome/esphome-hassio
stage: experimental
advanced: true
options:
  home_assistant_dashboard_integration: false
