name: Mailfilter
version: 4.0.1
slug: mailfilter
description: $'Rspamd邮件过滤器为Home Assistant

请注意，这个翻译可能不是完全准确的。Rspamd 是一个开源的垃圾邮件过滤系统，而 Home Assistant 是一个智能家居自动化平台。如果需要更精确的翻译或上下文信息，请告诉我更多细节。'
url: https://gh-proxy.com/github.com/erik73/hassio-addons
arch:
- aarch64
- amd64
- armv7
stage: experimental
init: false
ingress: true
panel_icon: mdi:filter
hassio_api: true
ingress_port: 1337
map:
- ssl:rw
options:
  enable_antivirus: false
  enable_dkim_signing: false
schema:
  enable_antivirus: bool
  enable_dkim_signing: bool
image: ghcr.nju.edu.cn/erik73/mailfilter/{arch}
