name: Tado Auto Assist
version: 1.6.2
slug: tado_aa
description: $'Tado自动辅助地理围栏和开窗检测

请注意，由于“Geofencing”和“open Window Detection”是技术术语，它们可能需要根据上下文进行适当的翻译。如果这些术语在特定领域或产品中有特定的含义，请提供更多的背景信息以便更准确地翻译。'
url: https://gh-proxy.com/github.com/FaserF/hassio-addons/tree/master/tado_aa
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
image: ghcr.nju.edu.cn/faserf/tado_aa-{arch}
init: false
options:
  username:
  password:
  minTemp: int(5, 25)
  maxTemp: int(5, 25)
  log_level: info
schema:
  username: str
  password: password
  minTemp: int
  maxTemp: int
  log_level: list(info|minimal)?
