name: Matterbridge
version: 1.3.2
slug: matterbridge
description: A simple chat bridge between different messanger apps
url: https://gh-proxy.com/github.com/FaserF/hassio-addons/tree/master/matterbridge
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
image: ghcr.nju.edu.cn/faserf/matterbridge-{arch}
map:
  - share:rw
init: false
panel_icon: mdi:bridge
options:
  config_path: "/share/matterbridge.toml"
  log_level: info
schema:
  config_path: str
  log_level: list(info|debug)?
