labels:
  maintainer: "Desmond Dong"
  io.hass.addon.changelog: |
    ## v1.0.1
    - Initial release of py-KMS addon for Home Assistant
    - First version of KMS server integration
  io.hass.addon.version: "v1.0.1"
  io.hass.addon.name: "py-KMS Home Assistant Addon"
  io.hass.addon.description: "A Home Assistant Addon for py-KMS."
  io.hass.addon.url: "https://github.com/Desmond-Dong/hassio-addons"
  io.hass.addon.arch: "amd64, armhf, armv7, aarch64, i386"
  io.hass.addon.init: "false"
  io.hass.addon.startup: "services"
  io.hass.addon.ingress: "true"
  io.hass.addon.ingress_port: "1688"
  io.hass.addon.panel_icon: "mdi:robot"
  io.hass.addon.map: |
    - /config/addons_config/py-kms:/kms/data
  io.hass.addon.ports: |
    1688/tcp: 1688
  io.hass.addon.ports_description: |
    1688/tcp: "py-KMS Server"
  io.hass.addon.hassio_api: "true"
  io.hass.addon.hassio_role: "manager"
  io.hass.addon.webui: "http://[HOST]:[PORT:1688]"