{
  "name": "py-kms",
  "version": "73bce0b-spad8",
  "slug": "py-kms",
  "description": "这是py-kms，一个用来激活Windows和Office的服务器",
  "codenotary": "djhhui@gmail.com",
  "url": "https://github.com/Desmond-Dong/hassio-addons",
  "arch": [
    "aarch64",
    "amd64",
    "armv7"
  ],
  "startup": "services",
  "image": "ghcr.nju.edu.cn/thespad/py-kms",
  "boot": "auto",
  "ingress": true,
  "ingress_port": 1688,
  "init": false,
  "hassio_api": true,
  "hassio_role": "manager",
  "ports": {
    "1688/tcp": 1688
  },
  "ports_description": {
    "1688/tcp": "KMS Server port"
  },
  "environment": {
    "PUID": "1000",
    "PGID": "1000",
    "TZ": "Asia/Shanghai"
  },
  "restart": "unless-stopped",
  "options": {},
  "schema": {},
  "log_level": "info"
}
