build_from:
  armv7: ghcr.nju.edu.cn/home-assistant/armv7-base-debian:bookworm
  aarch64: ghcr.nju.edu.cn/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.nju.edu.cn/home-assistant/amd64-base-debian:bookworm
  i386: ghcr.nju.edu.cn/home-assistant/i386-base-debian:bookworm
