name: tuya-convert BETA
version: 0.1.1
slug: tuya-convert
description: 泰雅转换-使用开源软件刷写泰雅/智能生活设备。测试版且不再维护！
url: https://gh-proxy.com/github.com/FaserF/hassio-addons/tree/master/tuya-convert
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
map:
  - share:rw
host_network: true
init: false
privileged:
  - NET_ADMIN
options:
  backup_path: "/share/tuya-convert/"
  firmware: tasmota.bin
  accept_eula: "false"
schema:
  backup_path: str
  firmware: str
  accept_eula: str
