name: tuya-convert BETA
version: 0.1.1
slug: tuya-convert
description: $'图中的文字是：

"Tuya Convert - Flash Tuya/Smart Life devices with open Source software. Beta and not being worked on anymore!"

翻译为中文如下：

“Tuya转换器 - 使用开源软件刷写Tuya/智能生活设备。这是一个测试版，不再被开发中！”'
url: https://gh-proxy.com/github.com/FaserF/hassio-addons/tree/master/tuya-convert
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
map:
  - share:rw
host_network: true
init: false
privileged:
  - NET_ADMIN
options:
  backup_path: "/share/tuya-convert/"
  firmware: tasmota.bin
  accept_eula: "false"
schema:
  backup_path: str
  firmware: str
  accept_eula: str
