---
build_from:
  aarch64: ghcr.nju.edu.cn/linuxserver/baseimage-debian:arm64v8-bookworm
  amd64: ghcr.nju.edu.cn/linuxserver/baseimage-debian:amd64-bookworm
codenotary:
  signer: alexandrep.github@gmail.com
