---
name: "Microsoft TTS"
description: microsoft_tts
version: "1.2.0"
slug: "wyoming_microsoft_tts"
init: false
arch:
  - aarch64
  - amd64
discovery:
  - wyoming
ports:
  "10200/tcp": null
options:
  debug_logging: false
  update_voices: true
schema:
  subscription_key: str
  service_region: str
  debug_logging: bool
  update_voices: bool
tmpfs: true
image: "ghcr.nju.edu.cn/hugobloem/{arch}-wyoming-microsoft-tts"
