name: MyIP
version: "v5.0.0"
upstream: latest
slug: myip
description: >-
  The best IP Toolbox. Easy to check what's your IPs, IP geolocation, check for DNS leaks, examine WebRTC connections, speed test, ping test, MTR test, check website availability, whois search and more!
arch:
  - amd64
  - aarch64
url: "https://gh-proxy.com/github.com/jdeath/homeassistant-addons"
ports:
  18966/tcp: 18966 
ports_description:
  18966/tcp: "Web Interface"
image: ghcr.nju.edu.cn/jason5ng32/myip
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:18966]"
ingress: false
ingress_port: 18966 
