build_from:
  amd64: homeassistant/amd64-base:latest
  armhf: docker.1ms.run/homeassistant/armhf-base:latest
  aarch64: docker.1ms.run/homeassistant/aarch64-base:latest
labels:
  maintainer: "Desmond Dong"
  io.hass.addon.changelog: |
    ## v0.6.2
    - Updated WeChat Server addon for Home Assistant
    - Enhanced performance and stability
    - Added APP_SECRET to configuration
  io.hass.addon.version: "v0.6.2"
  io.hass.addon.name: "WeChat Server"
  io.hass.addon.description: "这是一个公众号后台，连接智能助理帮你回话。关注微信号：<老王杂谈说> 获取更多内容吧"
  io.hass.addon.url: "https://mp.weixin.qq.com/s?__biz=MzUzNTExMDE2Mg==&mid=2247484640&idx=1&sn=c7b7cf843b10b7d3261f464c3cdea7fb&chksm=fa8b339dcdfcba8be7e968136912e9d0f142c5c947dcc6d28f35fbacfe28c3c96288619c4d0f&token=61213738&lang=zh_CN#rd"
  io.hass.addon.arch: "amd64, armhf, aarch64, armv7, i386"
  io.hass.addon.init: "false"
  io.hass.addon.startup: "services"
  io.hass.addon.ingress: "true"
  io.hass.addon.ingress_port: "8888"
  io.hass.addon.panel_icon: "mdi:wechat"
  io.hass.addon.map: |
    - /config/addons_config/wechat-server:/config/addons_config/wechat-server
  io.hass.addon.ports: |
    8888/tcp: 8888
  io.hass.addon.ports_description: |
    8888/tcp: "WeChat Server"
  io.hass.addon.hassio_api: "true"
  io.hass.addon.hassio_role: "manager"
  io.hass.addon.options: |
    TOKEN: "your_wechat_token"
    HOST: "0.0.0.0"
    APP_ID: "your_app_id"
    APP_SECRET: "your_app_secret"
    ENCODING_AES_KEY: "your_encoding_aes_key"
    ZhipuAI: "your_zhipuai_api_key"
    data_path: "/config/addons_config/wechat-server/"
  io.hass.addon.schema: |
    TOKEN: str
    HOST: str
    APP_ID: str
    APP_SECRET: str
    ENCODING_AES_KEY: str
    ZhipuAI: str
    data_path: str
  io.hass.addon.image: "docker.io/privoce/wechat-server"
  io.hass.addon.webui: "http://[HOST]:[PORT:8888]"
  io.hass.addon.watchdog: "http://[HOST]:[PORT:8888]"