{
  "name": "wechatbot-webhook",
  "version": "latest",
  "slug": "wechatbot-webhook",
  "description": "一个支持个人号消息收发的微信机器人，还未测试不要安装,目前有bug,会不停的让你扫描二维码，不要安装",
  "url": "https://github.com/Desmond-Dong/hassio-addons",
  "arch": ["aarch64", "amd64"],
  "startup": "application",
  "image": "dannicool/docker-wechatbot-webhook",
  "boot": "auto",
  "init": false,
  "webui": "http://[HOST]:[PORT:3001]/login?token=",
  "ports": {
    "3001/tcp": 3001
  },
  "options": {
    "recvd_msg_api": "",
    "login_api_token": "123",
    "disable_auto_login": false,
    "accept_recvd_msg_myself": false,
    "log_level": "default"
  },
  "schema": {
    "recvd_msg_api": "str?",
    "login_api_token": "str?",
    "disable_auto_login": "bool",
    "accept_recvd_msg_myself": "bool",
    "log_level": "list(default|quiet|debug)"
  }
}