name: "ConvertX"
version: "v0.12.0"
upstream: "v0.12.0"
slug: convertx
description: $'翻译：> - 一个自托管的在线文件转换器。支持831种不同的格式。使用TypeScript、Bun和Elysia编写。

---

**说明：**

- **自托管**：这意味着该应用程序不是基于云的，而是由用户自己管理和运行的。
- **在线文件转换器**：这是一个允许用户在浏览器中上传文件并转换为不同格式的工具。
- **支持831种不同的格式**：这表明它能够处理非常广泛的文件类型。
- **使用TypeScript、Bun和Elysia编写**：
  - **TypeScript** 是一种强类型的JavaScript超集，增加了类型检查功能，有助于开发大型项目时提高代码质量和可维护性。
  - **Bun** 是一个新兴的静态网站生成器和全栈 JavaScript 运行时环境，旨在简化 Web 开发流程。
  - **Elysia** 是一个轻量级的 Node.js 框架，专注于简洁性和性能优化。'
  A self-hosted online file converter. Supports 831 different formats. Written with TypeScript, Bun and Elysia
arch:
  - amd64
  - aarch64
url: "https://gh-proxy.com/github.com/jdeath/homeassistant-addons"
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: "Web Interface"
map:
  - type: addon_config
    read_only: false
    path: /app/data
environment:
  ACCOUNT_REGISTRATION: "false"
  HTTP_ALLOWED: "true"
  ALLOW_UNAUTHENTICATED: "true"
image: ghcr.nju.edu.cn/c4illin/convertx
boot: auto
startup: services
webui: "[PROTO:ssl]://[HOST]:[PORT:3000]"
panel_admin: false
ingress: false
ingress_port: 3000
