{
  "name": "集客AC控制器",
  "version": "2.2",
  "slug": "gecoos",
  "codenotary": "djhhui@gmail.com",
  "description": "一个集客AC控制器的 Home Assistant 加载项",
  "url": "https://github.com/Desmond-Dong/hassio-addons",
  "arch": ["aarch64", "amd64", "armv7", "armhf", "i386"],
  "startup": "services",
  "boot": "auto",
  "webui": "http://[HOST]:[PORT:8080]",
  "ports": {
    "8080/tcp": 8080
  },
  "options": {
    "showtip": 1,
    "debug": 0,
    "api_port": 60650,
    "token": 1,
    "lang": "zh",
    "passwd": "admin"
  },
  "ports_description": {
    "8080/tcp": "Web interface"
  },
  "schema": {
    "api_port": "int",
    "showtip": "int",
    "debug": "int",
    "token": "int",
    "lang": "str",
    "passwd": "str"
  },
  "hassio_role": "manager",
  "environment": {
    "GIN_MODE": "release"
  }
}
