name: Signal Messenger
url: https://gh-proxy.com/github.com/haberda/signal-addon/tree/master/
version: 0.91.0
slug: signal_messenger
arch:
- aarch64
- amd64
- armv7
description: $'信号消息（Signal Messenger）家庭助手插件

注：Signal Messenger 是一个开源的即时通讯应用，而 Home Assistant 是一个智能家居自动化平台。这个插件可能允许用户通过 Signal 消息与他们的智能家居设备进行交互。'
startup: services
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Rest-api port
options:
  mode: list(normal|native|json-rpc)
  AUTO_RECEIVE: true
  SIGNAL_CLI_CMD_TIMEOUT: 60
map:
- addon_config:rw
schema:
  mode: list(normal|native|json-rpc)
  AUTO_RECEIVE: bool
  SIGNAL_CLI_CMD_TIMEOUT: int
environment:
  SIGNAL_CLI_CONFIG_DIR: /config
image: ghcr.nju.edu.cn/haberda/signal_messenger/{arch}
