---
build_from:
  aarch64: ghcr.nju.edu.cn/home-assistant/aarch64-base:3.14
  amd64: ghcr.nju.edu.cn/home-assistant/amd64-base:3.14
  armhf: ghcr.nju.edu.cn/home-assistant/armhf-base:3.14
  armv7: ghcr.nju.edu.cn/home-assistant/armv7-base:3.14
  i386: ghcr.nju.edu.cn/home-assistant/i386-base:3.14
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  LIBCEC_VERSION: 6.0.2
